version: '3.8'

services:
    laravel:
        build:
            context: ./backend
        container_name: laravel-backend
        ports:
            - "8000:80"
        volumes:
            - ./backend:/var/www/html
        depends_on:
            - mysql
        networks:
            - appnet

    mysql:
        image: mysql:8.3
        container_name: laravel-mysql
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - appnet

    node:
        image: node:22
        container_name: vue-frontend
        working_dir: /app
        volumes:
            - ./frontend:/app
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run dev"
        networks:
            - appnet

networks:
    appnet:
        driver: bridge